### ISSUE TITLE
Document the --ignore-scripts option

### ISSUE THREAD

**Issue by givankin** [npm/docs#130]
This options is really handy and should be documented (at least on the https://docs.npmjs.com/misc/scripts page). The confusion about scripts is common (e.g. a prepublish that is run on install - but that's another issue, or just see here: https://github.com/npm/npm/issues/2817).

**Comment by KenanY** [comment]
@abbakym `docs.npmjs.com` pulls the docs from the main repo, [`npm/npm`](https://github.com/npm/npm) (in the `doc/` directory).

@othiym23 In how many places should this be documented? It is already in [`npm-config(7)`](https://docs.npmjs.com/misc/config#ignore-scripts), but just like https://github.com/npm/npm/pull/7444 I too think it should probably be documented in the pages of the commands it affects... but I think quite a few commands are affected by this flag (`install` and `run-script` to name a couple). Should we just do [`npm-scripts(7)`](https://docs.npmjs.com/misc/scripts)?

**Comment by othiym23** [comment]
@KenanY it's a reasonable question, but I don't have a really good answer for you. It seems like any option that's used by more than a couple commands should probably stay in `misc/npm-config.md`, unless there's something about that flag for a certain command that makes it especially interesting or dangerous. We should also 1. make the references between doc pages actual hotlinks (it's filed as an issue, but keeps falling down the priority queue because ＳＴＡＲＴＵＰ　ＬＩＦＥ) and 2. draw people's attention to those cross-links more frequently.

Also, we probably need to add a table of contents back to `npm-config.md`, because its current user experience is far from ergonomic. @zeke, I know you''re up to your butt in balligators right now, but do you have any thoughts on this looking down the road?

**Comment by ashleygwilliams** [comment]
hi @givankin ! while it is true that the docs you are discussing are pulled from the cli, i am working on building a guide for `scripts` and this should definitely go in there. be on the lookout for it! and thanks for filing the issue!

**Comment by givankin** [comment]
thanks @ashleygwilliams ! looking forward to seeing the guide!

**Comment by ashleygwilliams** [comment]
closing in favor of #498 (<-- consolidating all the scripts doc tickets to this one @givankin)
