### ISSUE TITLE
semver page markdown malformatted

### ISSUE THREAD

**Issue by redonkulus** [npm/docs#133]
https://docs.npmjs.com/misc/semver

The "Prerelease Identifiers" section has an example that is not closed properly, making the subsequent markdown unprocessed. I was going to fix it in this repo but I can't find that document, I'm not sure which repo it is in.

**Comment by othiym23** [comment]
Through a convoluted chain of dependencies, it's actually [the README](https://github.com/npm/node-semver/blob/master/README.md) for [`node-semver`](https://github.com/npm/node-semver). It may be possible we need to redeploy to catch all of the recent changes to the semver documentation, because we've made a couple tweaks to that section in the recent past.

**Comment by zeke** [comment]
Fixed! @othiym23 and I are working to better document the release process today.

https://docs.npmjs.com/misc/semver#prerelease-identifiers

![screen shot 2015-04-03 at 2 09 21 pm](https://cloud.githubusercontent.com/assets/2289/6989026/be780bb0-da0b-11e4-8c6d-b8000802e749.png)
