### ISSUE TITLE
npm package.json doc has duplicate entry of "npm-config"

### ISSUE THREAD

**Issue by HansS** [npm/docs#489]
just a small thing, but i was wondering!

**Comment by ashleygwilliams** [comment]
hi! the doc pages for `cli`, `files`, and `misc` live in the CLI repo. https://github.com/npm/npm/blob/master/doc/files/package.json.md

this duplication is actually because there are 2 npm-config pages for the cli docs:
- cli/npm-config: https://github.com/npm/npm/blob/master/doc/cli/npm-config.md
- misc/npm-config: https://github.com/npm/npm/blob/master/doc/misc/npm-config.md

closing this issue. please reopen on that repo!
