### ISSUE TITLE
Mac OS X El Capitan change from .profile to .bash_profile

### ISSUE THREAD

**Issue by fdoliveira** [npm/docs#658]
At https://docs.npmjs.com/getting-started/fixing-npm-permissions#fixing-npm-permissions can have a note for MAC OS X El Capitan to use .bash_profile instead of .profile?

**Comment by andyanderson** [comment]
Not just El Capitan, the default shell has been bash since Mac OS 10.4 “Tiger” in 2005. By default bash will not read .profile if it finds .bash_profile, even on Linux:

“After reading [/etc/profile], [bash] looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from _the first one_ that exists and is readable.”

I’d suggest replacing “Open or create a ~/.profile file and add this line:” with “Open or create a personal initialization file for your shell, e.g. ~/.profile for sh or ~/.bash_profile for bash or ~/.login for tcsh, and add this line:”

By the way, the last line in this block reads “NPM_CONFIG_PREFIX=~/.npm-global npm install -g jshint”, but I think it should just be “NPM_CONFIG_PREFIX=~/.npm-global”. I’d also recommend moving this line and the previous one *before* the test paragraph.

**Comment by fdoliveira** [comment]
Thanks for complete explanation, I agree with your suggestion it's more complete and give user the choice for which sheel it's your favorite.
