### ISSUE TITLE
--unsafe should be --unsafe-perms?

### ISSUE THREAD

**Issue by lholmquist** [npm/docs#739]
Looking at the enterprise docs for installing npme, https://docs.npmjs.com/enterprise/installation#2-install-npme-on-your-server , the command is 

`$ sudo npm install npme -g --unsafe`

I couldn't find what the --unsafe param did.  It is suggested that this should actually be --unsafe-perms : https://twitter.com/aredridel/status/769218584451096576

If so, i can send a PR

**Comment by lholmquist** [comment]
A PR is here for this,  https://github.com/npm/docs/pull/740

**Comment by ashleygwilliams** [comment]
hi! thanks for this!

it turns out that due to how npm config works, both `--unsafe` and `--unsafe-perm` do the same thing (shortest unambiguous prefix). that being said, codifying a shortcut is not great for documentation so i agree we should change this up!

for more info on what `--unsafe-perm` does, check this out:
https://github.com/npm/npm/blob/8fa75cd0313e3cea8459f89b79208461e54b033b/doc/misc/npm-scripts.md#user

**Comment by lholmquist** [comment]
@ashleygwilliams ah, gotcha.   yea, it was a little confusing that i couldn't find that flag.  tbh, i don't remember now why i was looking for it :)

**Comment by ashleygwilliams** [comment]
merged your commit! thanks again :) closed by #740
