### ISSUE TITLE
npm cache clean command not working with and without arguments in npm 5.5

### ISSUE THREAD

**Issue by acehema** [npm/docs#901]
I upgraded to npm 5.5 and I find that npm cache clean command is throwing an error . How to clean cache( only a part of the cache ) with an argument in npm 5.5 ? 

PS H:\> npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to
 be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     c:\nodejs\__npm-cache\_logs\2017-11-02T15_48_42_246Z-debug.log

**Comment by anapanadero** [comment]
I have the same problem.

**Comment by CarolynWriter** [comment]
Hi, this is the place for doc issues, so I alerted the appropriate team. Thanks for letting us know!

**Comment by iarna** [comment]
Hey y'all, as @CarolynWriter says, this isn't the appropriate venue for these questions. For this sort of question I'd suggest joining https://wealljs.org/ and asking in the #npm channel.

That being said, I can answer your question here:

There is no way to ask npm@5 to remove a specific entry from the cache.

If you are afraid that there's corruption in your cache you can ask npm to verify it manually: `npm cache verify`

Corrupted caches in npm@5 will be fixed when encountered at install time, but `npm cache verify` can sometimes save you some disk space.

And finally, if you're sure you want to **delete** your cache, you can do that, the answer is in the error message: _If you're sure you want to delete the entire cache, rerun this command with --force._ So that is: `npm cache clean --force`
